#! /bin/sh
# Guess values for system-dependent variables and create Makefiles.
# Generated by GNU Autoconf 2.69 for Greenplum Database 6.0.0-alpha.0.
#
# Report bugs to <support@greenplum.org>.
#
#
# Copyright (C) 1992-1996, 1998-2012 Free Software Foundation, Inc.
#
#
# This configure script is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.
#
# Copyright (c) 1996-2014, PostgreSQL Global Development Group
## -------------------- ##
## M4sh Initialization. ##
## -------------------- ##
sudo rm -Rf /usr/local/gpdb
make distclean
cd depends
make distclean
./configure
make
make install_local
sudo mkdir -p /usr/local/gpdb
sudo cp -R -L build/* /usr/local/gpdb
cd ..


./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb
make -j8
sudo make -j8 install


source /usr/local/gpdb/greenplum_path.sh
make create-demo-cluster
source gpAux/gpdemo/gpdemo-env.sh


make installcheck-world

